<?php return [
    "Nghề làm cha mẹ", 
    "Cảm thụ âm nhạc", 
    "Âm nhạc và công nghệ", 
    "Ngoại ngữ", 
    "Vẽ sáng tạo", 
    "Toán tư duy", 
    "Kỹ năng sống", 
    "Bóng Đá", 
    "Bóng rổ", 
    "Golf Kid", 
    "Kungfu Kid", 
    "Speaking Well", 
    "Bác sĩ gia đình", 
    "Tiếng Đức", 
    "Tiếng Hoa", 
    "Yoga", 
    "Yoga cười", 
    "Nghệ thuật lãnh đạo cộng đồng", 
    "Kiddie Ceo", 
    "Future Leader", 
    "Kinh doanh", 
    "Pro MC", 
    "Tin học và Công nghệ", 
    "Truyền thông chuyên nghiệp", 
    "Văn hóa gia đình", 
    "Văn hóa doanh nghiệp",
];
