<?php return [
    "Nghề làm cha mẹ", 
    "Tư duy ý chí nhà vô địch", 
    "MC Kid", 
    "Vẽ sáng tạo", 
    "Content \"Khác mới hay\"", 
    "Ứng dụng tự học tiếng Anh", 
    "Thiếu niên doanh nhân", 
    "Ngoại ngữ", 
    "Nhảy hiện đại", 
    "Cảm thụ âm nhạc", 
    "Speaking Well", 
    "Đàn piano", 
    "Kích hoạt tư duy và kỹ năng tự học tập cho trẻ", 
];
