<?php return [
    "Thiếu niên doanh nhân Israel", 
    "Ứng dụng học toán IXL", 
    "Cảm thụ âm nhạc", 
    "Monkey Math", 
    "Speaking well", 
    "Phát âm tiếng Anh chuẩn bản xứ ELSA Speak", 
    "Kích hoạt tư duy và kỹ năng tự học tập cho trẻ", 
    "MC Kid, Singer Kid", 
    "Monkey Junior", 
    "Mỹ thuật - Vẽ sáng tạo", 
    "Nghệ thuật viết content \"Khác mới hay\"", 
    "Huấn luyện Tư duy Ý chí Nhà Vô Địch", 
    "Tiếng Anh từ Mầm non đến lớp 12 trên IXL",
    "Nhạc cụ dân tộc Tranh, Sáo, Nhị, Bầu",
    "Nhạc cụ cổ điển Piano, Guitar, Violin",
    "Nghề làm Cha Mẹ",
];
