<?php return [
    [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/team-1.jpg',
        'title' => '',
        'contact' => [],
    ], [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/team-2.jpg',
        'title' => '',
        'contact' => [],
    ], [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/team-3.jpg',
        'title' => '',
        'contact' => [],
    ],
    [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/PX-02.jpg',
        'title' => '',
        'contact' => [],
    ],
    [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/PX-03.jpg',
        'title' => '',
        'contact' => [],
    ],
    [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/PX-04.jpg',
        'title' => '',
        'contact' => [],
    ],
    [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/PX-05.jpg',
        'title' => '',
        'contact' => [],
    ],
    [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/PX-06.jpg',
        'title' => '',
        'contact' => [],
    ],
    [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/PX-07.jpg',
        'title' => '',
        'contact' => [],
    ],
    [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/PX-08.jpg',
        'title' => '',
        'contact' => [],
    ],
    [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/PX-09.jpg',
        'title' => '',
        'contact' => [],
    ],
    [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/PX-11.jpg',
        'title' => '',
        'contact' => [],
    ],
    [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/PX-12.jpg',
        'title' => '',
        'contact' => [],
    ],
    [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/PX-13.jpg',
        'title' => '',
        'contact' => [],
    ],
    [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/PX-14.jpg',
        'title' => '',
        'contact' => [],
    ],
    [
        'name' => '',
        'avatar' => '/cdn/onepage/images/teachers/PX-01.jpg',
        'title' => '',
        'contact' => [],
    ],
];
